module {
  func @multiply_transpose(%arg0: !lift.array, %arg1: !lift.array)
  attributes  {lift.generic = true} {
    %0 = "lift.transpose"(%arg1) : (!lift.array) -> !lift.array loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":3:14)
    %1 = "lift.mul"(%arg0, %0) : (!lift.array, !lift.array) -> !lift.array loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":3:14)
    "lift.return"(%1) : (!lift.array) -> () loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":3:3)
  } loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":2:1)
  func @test(%arg0: !lift.array)
  attributes  {lift.generic = true} {
    %0 = "lift.constant"() {value = dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00], [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf64>} : () -> !lift.array<2, 3> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":7:19)
    %1 = "lift.reshape"(%0) : (!lift.array<2, 3>) -> !lift.array<2, 3> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":7:5)
    %2 = "lift.constant"() {value = dense<2.000000e+00> : tensor<1xf64>} : () -> !lift.array<1> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":8:21)
    "lift.print"(%arg0) : (!lift.array) -> () loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":9:5)
    "lift.return"() : () -> () loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":6:1)
  } loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":6:1)
  func @main() {
    %0 = "lift.constant"() {value = dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00], [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf64>} : () -> !lift.array<2, 3> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":13:17)
    %1 = "lift.reshape"(%0) : (!lift.array<2, 3>) -> !lift.array<2, 3> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":13:3)
    %2 = "lift.constant"() {value = dense<[1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00, 5.000000e+00, 6.000000e+00]> : tensor<6xf64>} : () -> !lift.array<6> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":14:17)
    %3 = "lift.reshape"(%2) : (!lift.array<6>) -> !lift.array<2, 3> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":14:3)
    %4 = "lift.generic_call"(%1, %3) {callee = "multiply_transpose"} : (!lift.array<2, 3>, !lift.array<2, 3>) -> !lift.array loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":15:11)
    %5 = "lift.generic_call"(%3, %1) {callee = "multiply_transpose"} : (!lift.array<2, 3>, !lift.array<2, 3>) -> !lift.array loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":16:11)
    "lift.print"(%5) : (!lift.array) -> () loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":17:3)
    %6 = "lift.constant"() {value = dense<2.000000e+00> : tensor<1xf64>} : () -> !lift.array<1> loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":19:17)
    %7 = "lift.generic_call"(%6) {callee = "Float"} : (!lift.array<1>) -> !lift.array loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":19:11)
    "lift.print"(%7) : (!lift.array) -> () loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":20:3)
    "lift.return"() : () -> () loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":12:1)
  } loc("../../projects/mlir/test/Dialect/Lift/simpleIRRecognitionExample.lift":12:1)
} loc(unknown)
